displayName=Guardians of the Rift Helper
author=BofaBear
build=standard
description=Displays info during the Guardians of the Rift minigame.
tags=minigame, overlay, guardians of the rift
plugins=com.datbear.GuardiansOfTheRiftHelperPlugin